# Generated by Django 5.0.1 on 2024-01-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LungsApp', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
